baseURL = "https://obrazslov.ru/"
languageCode = "ru-ru"
title = "Образ слов"
theme = "shared-assets"

[permalinks]
  posts = "/:year/:month/:filename.html"

[params]
  description = "База знаний экосистемы blago-nko"
  author = "blago-nko"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
